accepted_image_formats = [".jpg", ".jpeg", ".png", ".webp"]
accepted_video_formats  = [".mp4", ".webm", ".mkv"]

[image-input]
# The largest dimension of the baseline image, what faces and the 
# focus point are cropped from.
baseline_size = 1080

[image-output]
# The largest dimension of the output image, if in landscape this will be the
# width, if in portrait this will be the height
target_size = 600
quality = 30

# The percent of the smallest dimension of the image to crop from
# the center of the image to save in a higher resolution
focus_percent = 45

# The quality of the extracted parts of the image in greater resolution
face_quality = 40
focus_point_quality = 30

# The quality of the small parts of the image saved in higher resolution
# to preserve smaller details
detail_quality = 50

# Saves the full image in low quality as the baseline image, which can be
# viewed without any restoration processing, but adds ~4kb to the backup file.
# This is useful if a full preview of the image is wanted or if the user
# is worried about not being able to run the restoration processing.
# Without this option, only a small portion of the image will be shown when
# viewed without any restoration processing.
full_baseline = false

# Metadata tags specified by the user to keep. Will significantly increase
# the size of the output file so there are no defaults.
user_metadata_tags = []

[video-output]
target_size = 720
frame_rate = 8
crf = 50
audio_bitrate = "32k"

[debug]
enabled = false