accepted_image_formats = [".jpg", ".jpeg", ".png", ".webp"]
accepted_video_formats  = [".mp4", ".webm", ".mkv"]

[image-input]
# The largest dimension of the baseline image, what faces and the 
# focus point are cropped from.
baseline_size = 1080
baseline_quality = 90

[image-output]
# The largest dimension of the output image, if in landscape this will be the
# width, if in portrait this will be the height
target_size = 256
quality = 25

# The percent of the smallest dimension of the image to crop from
# the center of the image to save in a higher resolution
focus_percent = 40
# The percent of the baseline image resolution to use for the center
focus_resolution_percent = 100

# Metadata tags specified by the user to keep. Will significantly increase
# the size of the output file so there are no defaults.
user_metadata_tags = []

[video-output]
target_size = 192
crf = 25
format = ".webm"
video_bitrate = "16k"
audio_bitrate = "16k"